# docker-compose.yaml

services:
  dev_sandbox:
    build:
      context: .
      dockerfile: Containerfile
    container_name: pentarchy_dev_env
    volumes:
      - .:/app:z
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
    stdin_open: true
    tty: true